### ISSUE TITLE
Figure out a color scheme for splash page

### ISSUE THREAD

**Issue by versionalt** [jeffbautista/jv-slack-bot#1]
**1. Review https://coolors.co/ for colors**

**2. Pick a color scheme**
1st choice
![jvslackbotcolorscheme1](https://cloud.githubusercontent.com/assets/12492121/24368747/9f89604a-12ef-11e7-9c4e-036c440644eb.png)

2nd choice
![001](https://cloud.githubusercontent.com/assets/12492121/24369192/313d02e8-12f1-11e7-91c3-18b79443f042.png)

3rd choice
![002](https://cloud.githubusercontent.com/assets/12492121/24369216/3ff92cd0-12f1-11e7-9d8d-cb0e3ecfe96f.png)

4th choice
![006](https://cloud.githubusercontent.com/assets/12492121/24369339/aaeb9258-12f1-11e7-929a-197db002d4f9.png)

5th choice
![005](https://cloud.githubusercontent.com/assets/12492121/24369324/a2e19b16-12f1-11e7-9846-21d85c01146f.png)
**3. Implement it**
Decide which colors will be for [Background, primary text, secondary text, header, footer]

**Comment by versionalt** [comment]
@jeffbautista What do you think about these color schemes?

**Comment by jb9000** [comment]
@ver2point0 I like 2, 4, and 5.  Not sure why I'm not receiving GitHub email notifications.  Tried changing some settings - hopefully that works

**Comment by versionalt** [comment]
@jeffbautista 2 is my favorite! I think we should go with that color scheme. Which one would you choose?

**Comment by jb9000** [comment]
@ver2point0 - let's go with #2 then!  FYI - my email notifications still aren't working so I'll just keep checking back here until I figure it out.

**Comment by versionalt** [comment]
@jeffbautista cool.
