### ISSUE TITLE
Find out what other BTL teams' are target date:  End of April

### ISSUE THREAD

**Issue by jb9000** [jeffbautista/jv-slack-bot#9]
Ask in Slack

**Comment by jb9000** [comment]
From 3/23:  

"The final deadline is month away. But, some of you may finish in a week, two weeks or take the month."  (https://chingu-wombats.slack.com/archives/C4NKZU9DH/p1490290153144527)

"Keep in mind the project has 2 parts - recreating an existing splash page, then brainstorming a cool bot and creating a splash page for that... (https://chingu-wombats.slack.com/archives/C4NKZU9DH/p1490290461250138)

"From there, who knows, maybe some teams will get crazy and learn a little node and create their bots. If not, there’s a possibility that next cohort someone will make that bot and you’ll get credit for being a part of that team. I’m kinda hoping to make that a build.to.learn for the backend cohorts next month “pick a splash page-pivot” and make it!"

**Comment by versionalt** [comment]
@jeffbautista Good stuff. So we're on our way to creating a bot and launching it.
